name: Run MATLAB Build on Self-Hosted Runner
on: [push, pull_request]
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run build
        uses: matlab-actions/run-build@v1
